---
- name: Update a single plugin
  shell: "PATH=$HOME/bin:$PATH;cv ext:download --filter-status=* --filter-ready=* --no-install --force {{ item.key }}"
  args:
    chdir: "{{ webroot }}"
  become: yes
  become_user: "{{ run_as_user }}"
  notify: Apply extension database upgrades

  #- name: Apply CiviDiscount patch
  # patch:
  #   src: "{{ role_path }}/files/cividiscount-free-event-fix.diff"
  #   backup: false
  #   basedir: "{{ webroot }}/{{ civicrm_custom_path }}/extensions/cividiscount"
  #   strip: 1
  # become: yes
  # when: item.key == "cividiscount"

- name: git add the plugin
  command: git add -v -A
  args:
    chdir: "{{ webroot }}"
  register: add_result
  become: yes
  become_user: "{{ run_as_user }}"
  changed_when: add_result.stdout != ''
  failed_when: add_result.stderr != ''

- name: git commit Civi + patches
  command: "git commit -m 'Civi extension upgrade: {{ item.key }} {{ item.upgradeVersion }}'"
  args:
    chdir: "{{ webroot }}"
  register: commit_result
  become: yes
  become_user: "{{ run_as_user }}"
  changed_when: commit_result.rc == 0
  failed_when: not(commit_result.rc == 0 or 'nothing to commit, working tree clean' in commit_result.stdout_lines)

- name: git push
  command: "git push"
  args:
    chdir: "{{ webroot }}"
  register: push_result
  become: yes
  become_user: "{{ run_as_user }}"
  when: git_repo_push_url is not search("https://")
  changed_when: push_result.rc == 0 and push_result.stderr != 'Everything up-to-date'
  failed_when: not(push_result.rc == 0)
